### ISSUE TITLE
Type parameters

### ISSUE THREAD

**Issue by rrdelaney** [rrdelaney/ReasonablyTyped#10]
Couple places they can be used:
* [x] Function declarations
* [x] Method declarations
* [x] Class declarations
* [x] Interface declarations

**Comment by bbqbaron** [comment]
I'd like to help bite something off here (really just trying to help with Reason, so I'm also open to direction, but if one of these is helpful). If no preference, in classes?

**Comment by rrdelaney** [comment]
There's some problems with class type params right now that I'm working on - but if you want to take another issue #12 would be awesome!
