### ISSUE TITLE
Promise support

### ISSUE THREAD

**Issue by rrdelaney** [rrdelaney/ReasonablyTyped#12]
No promises right now 😿

**Comment by bbqbaron** [comment]
For anyone who wanders along, I'm hoping to take this.

**Comment by rrdelaney** [comment]
A good place to start is probably here: https://github.com/rrdelaney/ReasonablyTyped/blob/master/src/retyped/modulegen.re#L245.

That's where we pick up named types and convert them

**Comment by rrdelaney** [comment]
Closed by #13
