### ISSUE TITLE
Multiple modules

### ISSUE THREAD

**Issue by rrdelaney** [rrdelaney/ReasonablyTyped#15]
Handle cases like:

```js
declare module 'test/one' {
  // ...
}

declare module 'test/two' {
  // ...
}
```

Right now we get the name from the first module and flatten declarations.

**Comment by bbqbaron** [comment]
I can pick this up. What did you have in mind if there's a clash? That is, if eg there's a `test/one.foo` and a `test/two.foo` and we can't just create `external foo`?

* Prefix the reason name with the module name? Eg `one_foo` and `two_foo`?
* Emit separate files for separate modules?

**Comment by rrdelaney** [comment]
I think the best option is to have nested modules inside the file, like:

```reason
module One = {
  /* ... */
};

module Two = {
  /* ... */
};
```

That way addressing `library/component` becomes `Library.Component`.

The issue comes where we have something like:

```js
declare module 'a' {
  // ...
}

declare module 'b' {
  // ...
}
```

Maybe just throw an error for now if there's multiple modules and more than one doesn't contain `/` or `-`. What are your thoughts?
