### ISSUE TITLE
DefinitelyTyped test suite

### ISSUE THREAD

**Issue by rrdelaney** [rrdelaney/ReasonablyTyped#20]
We currently have a test suite running against FlowTyped, but it would be great if we also had one to run against DefinitelyTyped.

See the [FlowTyped test runner](https://github.com/rrdelaney/ReasonablyTyped/blob/master/src/__tests__/flow-typed.js) for more information about how to implement this one. We might have to include DefinitelyTyped as a git submodule.

**Comment by fstoerkle** [comment]
#22 adds a `DefinitelyTyped` test suite
