### ISSUE TITLE
Date support

### ISSUE THREAD

**Issue by rrdelaney** [rrdelaney/ReasonablyTyped#31]
We don't support built-in JS date objects! We should, and it shouldn't be too difficult.

This is mostly just adding another case to [`named_to_bstype`](https://github.com/rrdelaney/ReasonablyTyped/blob/master/src/retyped/modulegen.re#L288-L362) and adding a new [`BsType`](https://github.com/rrdelaney/ReasonablyTyped/blob/master/src/retyped/modulegen.re#L59-L84), then rendering the results in [`bstype_to_code`](https://github.com/rrdelaney/ReasonablyTyped/blob/master/src/retyped/codegen.re#L73-L172).

The [`Js.Date`](https://bucklescript.github.io/bucklescript/api/Js.Date.html) documentation should be helpful here too

**Comment by SllyQ** [comment]
I'll take it
