### ISSUE TITLE
Update Test Expectations?

### ISSUE THREAD

**Issue by bbqbaron** [rrdelaney/ReasonablyTyped#36]
I think [this](https://github.com/rrdelaney/ReasonablyTyped/commit/9f987a9161cf9a01e1348ba89303b9dd68005074) commit introduced a number of compiler test failures. Not sure of background, but I thought I'd at least register it. Since the commit message was `Stop union types in parameters from generating precode`, perhaps the fixtures are just out of date?

E.g. `duplicate-type-params` seems to have dropped:

```
type union_of_number_or_string =
  | Number float
  | String string;

type number_or_string;

external number_or_string : union_of_number_or_string => number_or_string =
  "Array.prototype.shift.call" [@@bs.val];
```

**Comment by rrdelaney** [comment]
I broke the test case a little while ago 😅 I was in the middle of a feature I was finishing up and thought I'd push soon, then other things came up - I'll fix them tonight

**Comment by rrdelaney** [comment]
Tests should be all fixed 😄
