### ISSUE TITLE
String literal seems cause syntax error

### ISSUE THREAD

**Issue by kogai** [rrdelaney/ReasonablyTyped#50]
When ReasonablyTyped attempt to convert code includes string literal, it generates incorrect syntax

### Input

```
declare module 'literal-type' {
  declare export function f(x: "a" | "b"): void;
}
```

### Output

```
[@bs.module "literal-type"] external f : (~x:([`a | `b] [@bs.string])) => unit = "";
```

### Probably we expect

```
[@bs.module "literal-type"] external f : (~x:([@bs.string] [`a | `b])) => unit = "";
```

* **ReasonablyTyped version:** (output of `retyped --version`)

`0.13.0` (build from source code manually)

* **bs-platform version:** (output of `bsc -version`)

`BuckleScript 2.2.2 (Using OCaml4.02.3+BS )`

**Comment by kogai** [comment]
Additional,
To resolve this issue seems like `a good first issue`, and it would be an honor for me to tackle to fix it if I can.

**Comment by rrdelaney** [comment]
Hey @kogai thanks for reporting the issue and offering to help 😁 this would be a great first issue!

Sorry the contributing docs are a bit rough right now, but running “yarn install” should get you up and running. I recommend checking out https://github.com/rrdelaney/ReasonablyTyped/blob/master/src/bsTypeReason.re

**Comment by kogai** [comment]
Thanks 🙏 
And thanks to using bucklescript, building executable was pretty straightforward 👍 

I created PR #51, and when you'd ready to review, please make sure it and point out something noticed 🙏

**Comment by rrdelaney** [comment]
Closed by your PR 👍
