### ISSUE TITLE
Spread parameters

### ISSUE THREAD

**Issue by rrdelaney** [rrdelaney/ReasonablyTyped#7]
Rest spread parameters are not yet supported: 

```js
declare function add(...nums): number
```

**Comment by bbqbaron** [comment]
Mind if I have a try at this?

**Comment by rrdelaney** [comment]
Go for it! You'll probably want to look around here: https://github.com/rrdelaney/ReasonablyTyped/blob/master/src/retyped/modulegen.re#L103

I recently refactored a bunch of code, so if you need help let me know 😄 I'm @rrdelaney on the ReasonML discord - feel free to PM me

**Comment by rrdelaney** [comment]
Closed by #9. Thanks @bbqbaron!!
